"""initial durable execution schema

Revision ID: 7b38f4d2f5cb
Revises:
"""

import sqlalchemy as sa
from alembic import op

import control_plane.database

revision = "7b38f4d2f5cb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admission", sa.Column("id", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("id")
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("image", sa.String(length=256), nullable=False),
        sa.Column("command", sa.JSON(), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("cpu_required", sa.Float(), nullable=False),
        sa.Column("memory_required_mb", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=256), nullable=True),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("traceparent", sa.String(length=128), nullable=False),
        sa.Column("attempts_count", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("created_at", control_plane.database.UTCDateTime(timezone=True), nullable=False),
        sa.Column("eligible_at", control_plane.database.UTCDateTime(timezone=True), nullable=False),
        sa.Column("scheduled_at", control_plane.database.UTCDateTime(timezone=True), nullable=True),
        sa.Column("started_at", control_plane.database.UTCDateTime(timezone=True), nullable=True),
        sa.Column("finished_at", control_plane.database.UTCDateTime(timezone=True), nullable=True),
        sa.CheckConstraint("cpu_required > 0 AND memory_required_mb > 0"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        "ix_jobs_schedule",
        "jobs",
        ["status", "eligible_at", "priority", "created_at"],
        unique=False,
    )
    op.create_table(
        "workers",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("cpu_total", sa.Float(), nullable=False),
        sa.Column("memory_total_mb", sa.Integer(), nullable=False),
        sa.Column("cpu_available", sa.Float(), nullable=False),
        sa.Column("memory_available_mb", sa.Integer(), nullable=False),
        sa.Column("cpu_reserved", sa.Float(), nullable=False),
        sa.Column("memory_reserved_mb", sa.Integer(), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column(
            "last_heartbeat", control_plane.database.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("heartbeats_count", sa.Integer(), nullable=False),
        sa.Column("failures_count", sa.Integer(), nullable=False),
        sa.CheckConstraint("cpu_reserved >= 0 AND memory_reserved_mb >= 0"),
        sa.CheckConstraint("cpu_total > 0 AND memory_total_mb > 0"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "job_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=128), nullable=False),
        sa.Column("worker_session", sa.String(length=36), nullable=False),
        sa.Column("lease_token", sa.String(length=36), nullable=False),
        sa.Column(
            "lease_expires_at", control_plane.database.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "scheduled_at", control_plane.database.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("started_at", control_plane.database.UTCDateTime(timezone=True), nullable=True),
        sa.Column("finished_at", control_plane.database.UTCDateTime(timezone=True), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(length=256), nullable=True),
        sa.Column("logs", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_attempt_active", "job_attempts", ["status", "lease_expires_at"], unique=False
    )
    op.create_index("ix_attempt_job_number", "job_attempts", ["job_id", "number"], unique=True)
    op.add_column(
        "job_attempts",
        sa.Column("eligible_at", control_plane.database.UTCDateTime(), nullable=False),
    )
    op.create_index(
        "uq_active_attempt_job",
        "job_attempts",
        ["job_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('SCHEDULED','RUNNING','CANCEL_REQUESTED')"),
        sqlite_where=sa.text("status IN ('SCHEDULED','RUNNING','CANCEL_REQUESTED')"),
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("created_at", control_plane.database.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["job_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_artifacts_job_id"), "artifacts", ["job_id"], unique=False)
    op.create_table(
        "job_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("created_at", control_plane.database.UTCDateTime(timezone=True), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["job_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_events_job_id"), "job_events", ["job_id"], unique=False)
    op.bulk_insert(sa.table("admission", sa.column("id", sa.Integer())), [{"id": 1}])
    op.create_table(
        "worker_heartbeats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("worker_id", sa.String(128), sa.ForeignKey("workers.id"), nullable=False),
        sa.Column("session_id", sa.String(36), nullable=False),
        sa.Column("created_at", control_plane.database.UTCDateTime(), nullable=False),
        sa.Column("cpu_available", sa.Float(), nullable=False),
        sa.Column("memory_available_mb", sa.Integer(), nullable=False),
        sa.Column("running_jobs", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_worker_heartbeats_worker_id", "worker_heartbeats", ["worker_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index("ix_worker_heartbeats_worker_id", table_name="worker_heartbeats")
    op.drop_table("worker_heartbeats")
    op.drop_index("uq_active_attempt_job", table_name="job_attempts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_events_job_id"), table_name="job_events")
    op.drop_table("job_events")
    op.drop_index(op.f("ix_artifacts_job_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index("ix_attempt_job_number", table_name="job_attempts")
    op.drop_index("ix_attempt_active", table_name="job_attempts")
    op.drop_table("job_attempts")
    op.drop_table("workers")
    op.drop_index("ix_jobs_schedule", table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("admission")
    # ### end Alembic commands ###
