# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import engine_pb2 as engine__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerControlStub:
    """Worker credentials are transported as bearer authorization metadata on every RPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/strata.v1.WorkerControl/Register',
                request_serializer=engine__pb2.RegisterRequest.SerializeToString,
                response_deserializer=engine__pb2.RegisterReply.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/strata.v1.WorkerControl/Heartbeat',
                request_serializer=engine__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=engine__pb2.HeartbeatReply.FromString,
                _registered_method=True)
        self.Poll = channel.unary_unary(
                '/strata.v1.WorkerControl/Poll',
                request_serializer=engine__pb2.PollRequest.SerializeToString,
                response_deserializer=engine__pb2.PollReply.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/strata.v1.WorkerControl/Start',
                request_serializer=engine__pb2.AttemptRequest.SerializeToString,
                response_deserializer=engine__pb2.Empty.FromString,
                _registered_method=True)
        self.Complete = channel.unary_unary(
                '/strata.v1.WorkerControl/Complete',
                request_serializer=engine__pb2.CompleteRequest.SerializeToString,
                response_deserializer=engine__pb2.Empty.FromString,
                _registered_method=True)
        self.PutLogs = channel.unary_unary(
                '/strata.v1.WorkerControl/PutLogs',
                request_serializer=engine__pb2.LogsRequest.SerializeToString,
                response_deserializer=engine__pb2.Empty.FromString,
                _registered_method=True)
        self.PutArtifact = channel.unary_unary(
                '/strata.v1.WorkerControl/PutArtifact',
                request_serializer=engine__pb2.ArtifactRequest.SerializeToString,
                response_deserializer=engine__pb2.ArtifactReply.FromString,
                _registered_method=True)
        self.InputManifest = channel.unary_unary(
                '/strata.v1.WorkerControl/InputManifest',
                request_serializer=engine__pb2.AttemptRequest.SerializeToString,
                response_deserializer=engine__pb2.InputManifestReply.FromString,
                _registered_method=True)
        self.ReadInput = channel.unary_stream(
                '/strata.v1.WorkerControl/ReadInput',
                request_serializer=engine__pb2.ReadInputRequest.SerializeToString,
                response_deserializer=engine__pb2.InputChunk.FromString,
                _registered_method=True)
        self.Cluster = channel.unary_unary(
                '/strata.v1.WorkerControl/Cluster',
                request_serializer=engine__pb2.Empty.SerializeToString,
                response_deserializer=engine__pb2.ClusterReply.FromString,
                _registered_method=True)
        self.InspectOrphans = channel.unary_unary(
                '/strata.v1.WorkerControl/InspectOrphans',
                request_serializer=engine__pb2.OrphanRequest.SerializeToString,
                response_deserializer=engine__pb2.OrphanReply.FromString,
                _registered_method=True)
        self.RuntimeExchange = channel.unary_unary(
                '/strata.v1.WorkerControl/RuntimeExchange',
                request_serializer=engine__pb2.RuntimeRequest.SerializeToString,
                response_deserializer=engine__pb2.RuntimeReply.FromString,
                _registered_method=True)


class WorkerControlServicer:
    """Worker credentials are transported as bearer authorization metadata on every RPC.
    """

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Poll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Complete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InputManifest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadInput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InspectOrphans(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RuntimeExchange(self, request, context):
        """Bounded workload IPC; credentials stay in the trusted agent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=engine__pb2.RegisterRequest.FromString,
                    response_serializer=engine__pb2.RegisterReply.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=engine__pb2.HeartbeatRequest.FromString,
                    response_serializer=engine__pb2.HeartbeatReply.SerializeToString,
            ),
            'Poll': grpc.unary_unary_rpc_method_handler(
                    servicer.Poll,
                    request_deserializer=engine__pb2.PollRequest.FromString,
                    response_serializer=engine__pb2.PollReply.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=engine__pb2.AttemptRequest.FromString,
                    response_serializer=engine__pb2.Empty.SerializeToString,
            ),
            'Complete': grpc.unary_unary_rpc_method_handler(
                    servicer.Complete,
                    request_deserializer=engine__pb2.CompleteRequest.FromString,
                    response_serializer=engine__pb2.Empty.SerializeToString,
            ),
            'PutLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.PutLogs,
                    request_deserializer=engine__pb2.LogsRequest.FromString,
                    response_serializer=engine__pb2.Empty.SerializeToString,
            ),
            'PutArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.PutArtifact,
                    request_deserializer=engine__pb2.ArtifactRequest.FromString,
                    response_serializer=engine__pb2.ArtifactReply.SerializeToString,
            ),
            'InputManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.InputManifest,
                    request_deserializer=engine__pb2.AttemptRequest.FromString,
                    response_serializer=engine__pb2.InputManifestReply.SerializeToString,
            ),
            'ReadInput': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadInput,
                    request_deserializer=engine__pb2.ReadInputRequest.FromString,
                    response_serializer=engine__pb2.InputChunk.SerializeToString,
            ),
            'Cluster': grpc.unary_unary_rpc_method_handler(
                    servicer.Cluster,
                    request_deserializer=engine__pb2.Empty.FromString,
                    response_serializer=engine__pb2.ClusterReply.SerializeToString,
            ),
            'InspectOrphans': grpc.unary_unary_rpc_method_handler(
                    servicer.InspectOrphans,
                    request_deserializer=engine__pb2.OrphanRequest.FromString,
                    response_serializer=engine__pb2.OrphanReply.SerializeToString,
            ),
            'RuntimeExchange': grpc.unary_unary_rpc_method_handler(
                    servicer.RuntimeExchange,
                    request_deserializer=engine__pb2.RuntimeRequest.FromString,
                    response_serializer=engine__pb2.RuntimeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'strata.v1.WorkerControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('strata.v1.WorkerControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerControl:
    """Worker credentials are transported as bearer authorization metadata on every RPC.
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strata.v1.WorkerControl/Register',
            engine__pb2.RegisterRequest.SerializeToString,
            engine__pb2.RegisterReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strata.v1.WorkerControl/Heartbeat',
            engine__pb2.HeartbeatRequest.SerializeToString,
            engine__pb2.HeartbeatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Poll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strata.v1.WorkerControl/Poll',
            engine__pb2.PollRequest.SerializeToString,
            engine__pb2.PollReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strata.v1.WorkerControl/Start',
            engine__pb2.AttemptRequest.SerializeToString,
            engine__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Complete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strata.v1.WorkerControl/Complete',
            engine__pb2.CompleteRequest.SerializeToString,
            engine__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strata.v1.WorkerControl/PutLogs',
            engine__pb2.LogsRequest.SerializeToString,
            engine__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strata.v1.WorkerControl/PutArtifact',
            engine__pb2.ArtifactRequest.SerializeToString,
            engine__pb2.ArtifactReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InputManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strata.v1.WorkerControl/InputManifest',
            engine__pb2.AttemptRequest.SerializeToString,
            engine__pb2.InputManifestReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/strata.v1.WorkerControl/ReadInput',
            engine__pb2.ReadInputRequest.SerializeToString,
            engine__pb2.InputChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strata.v1.WorkerControl/Cluster',
            engine__pb2.Empty.SerializeToString,
            engine__pb2.ClusterReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InspectOrphans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strata.v1.WorkerControl/InspectOrphans',
            engine__pb2.OrphanRequest.SerializeToString,
            engine__pb2.OrphanReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RuntimeExchange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/strata.v1.WorkerControl/RuntimeExchange',
            engine__pb2.RuntimeRequest.SerializeToString,
            engine__pb2.RuntimeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
